- name: Install vector | Download vector rpm distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: 0644
- name: Install vector | Install vector rpm package
  become: true
  ansible.builtin.yum:
    name: vector-{{ vector_version }}.rpm
    disable_gpg_check: true
  notify: Restart vector service
  ignore_errors: "{{ ansible_check_mode }}"
