---
# tasks file for vector-role
- name: Install vector | Download vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: 0644
- name: Install vector | Install vector package
  become: true
  ansible.builtin.yum:
    name: vector-{{ vector_version }}.rpm
  notify: Restart vector service
  ignore_errors: "{{ ansible_check_mode }}"
- name: Install vector | Delete default vector config
  become: true
  ansible.builtin.file:
    path: /etc/vector/vector.toml
    state: absent
- name: Install vector | Set default vector config file for service
  become: true
  ansible.builtin.template:
    src: "templates/vector.j2"
    dest: "{{ vector_default_config_file }}"
    mode: 0644
  notify: Restart vector service
- name: Install vector | Vector config from template
  become: true
  ansible.builtin.template:
    src: "templates/vector.yml.j2"
    dest: "/etc/vector/vector.yml"
    mode: 0644
  notify: Restart vector service
- name: Install vector | Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Install vector | Check if vector started
  ansible.builtin.service_facts:
  register: temp__service_facts
  until: temp__service_facts.ansible_facts.services["vector.service"].state == 'running'
  retries: 20
  delay: 2
  ignore_errors: "{{ ansible_check_mode }}"
